
[[artifacts]]
git-tree-sha1 = "c8a9a5786ac81856193d10873974af604dfaabed"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.3.1/artifacts-linux-x86_64.tar.gz"
    sha256 = "aaa97c1e5014077f8d2b20231b179a14a238ff9de38775820cd838bfc0074439"

[[artifacts]]
git-tree-sha1 = "1211422f4576ce5eddb6cd4a24dd0147be998bbe"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.3.1/artifacts-win64.tar.gz"
    sha256 = "0f0aa43147609c1e2051e01af450649d6c797ebb1ccd5474a1966f29e727c9d1"

