
[[artifacts]]
git-tree-sha1 = "fa92314ee396ebfea2603750935f76557dc6ff21"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.4.1/artifacts-linux-x86_64.tar.gz"
    sha256 = "40a72ce5fca635b19218f509dcf86f1f349ee80f4a9b97fb4baec843d09f85b1"

[[artifacts]]
git-tree-sha1 = "e669c9736d633e0219c5f9cfa10ae39bb0f9c377"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.4.1/artifacts-win64.tar.gz"
    sha256 = "a66baba52e68b1a3e01f6d258fa9e7ab6c6bc098b55a4995ebb2ef1aa52b9fc3"

