
[[artifacts]]
git-tree-sha1 = "c8a9a5786ac81856193d10873974af604dfaabed"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.3.2/artifacts-linux-x86_64.tar.gz"
    sha256 = "edce59ef1c6c9e0dd7fd9ff00f271cb899da1afbc4e3de08f51304a475ac69cf"

[[artifacts]]
git-tree-sha1 = "98b35f7fb1b06477a70781342895ed5aefc375b3"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.3.2/artifacts-win64.tar.gz"
    sha256 = "16d79bf511beca89c7f70fef6ae95bcf14be84459d63a3721ef1fccd50a24fbd"

