[artifacts]
git-tree-sha1 = "4f6365130260f932784b99428223cb4c840a52f1"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.1.0-b/artifacts-linux-x86_64.tar.gz"
    sha256 = "e28c913b7758a432cfc12fe559779ef19cd0b330903e8b4482900fa489615d7f"
    os = "linux"
    arch = "x86_64"
