
[[artifacts]]
git-tree-sha1 = "fa92314ee396ebfea2603750935f76557dc6ff21"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.4.0/artifacts-linux-x86_64.tar.gz"
    sha256 = "541190e685c26b3e07122e3f873612c2989f3e3acfb0fe00744240c3cb76f471"

[[artifacts]]
git-tree-sha1 = "121f4b7a10d52d9413ad3bd0d4c8b7c1b7148621"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.4.0/artifacts-win64.tar.gz"
    sha256 = "3cd01a08352f15544b2e7d8c9bf911964148817a1dfd46be91b0eacab8486b31"

